### ISSUE TITLE
Improve search page

### ISSUE THREAD

**Issue by krjackso** [lucidsoftware/cashy#9]
* Search results should be like browse results where you see asset info instead of linking directly to the asset
* After searching the search box is emptied.  Would be nice if it kept the value from the last search.
* Highlight the matching portion of the search term in results

**Comment by msiebert** [comment]
first and third improvements were completed by @krjackso

**Comment by krjackso** [comment]
Not sure we should do the 2nd one.  It was a good thought until I tried it, now it seems weird after using it for a while

**Comment by msiebert** [comment]
Shall we just close this issue then?
